name: Deploy to Proxmox CT
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_CLIENT_SECRET }}
          tags: tag:ci

      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.TS_CLIENT_IP }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/fuju/sns-fe
            git pull origin main
            npm install && npm run build
            rm -rf /var/www/fuju/*
            cp -r ./dist /var/www/fuju/
